### ISSUE TITLE
Metadata minute text always has "s"

### ISSUE THREAD

**Issue by mutageneral** [LordMathis/hugo-theme-nightfall#11]
I made a small post and the metadata under the post said "0 minutes" but it should be "0 minute". There should be an if statement, I think. I don't know much more than that.

**Comment by LordMathis** [comment]
Apparently Hugo supports this directly https://gohugo.io/content-management/multilingual/#query-a-singularplural-translation
It should be done together with #13

**Comment by LordMathis** [comment]
Closing this issue as it is tracked in #13
