### ISSUE TITLE
RSS configuration

### ISSUE THREAD

**Issue by Harshil-Jani** [LordMathis/hugo-theme-nightfall#16]
Does the nightfall theme has any default RSS configuration which we can use for our blog posts ? 
Or is there a way to do this manually from our project ?

**Comment by LordMathis** [comment]
By default hugo generates RSS feed which will be available at `/index.xml`. The theme currently doesn't offer any RSS customization but you can customize it in your project [https://gohugo.io/templates/rss/](https://gohugo.io/templates/rss/)
