### ISSUE TITLE
Request: Visibility of tags/taxonomies inside single.html

### ISSUE THREAD

**Issue by jens1o** [LordMathis/hugo-theme-nightfall#2]
Hey there :)

I really like your theme. Thank you so much for your work and all the effort you folks put into this!
I think it would be great to have support for taxonomies, like a tagging feature, e.g. https://github.com/luizdepra/hugo-coder/blob/a198b8eb15c0d1a25baf7574bfebeae9be1abcf4/layouts/posts/single.html#L28-L30 (see https://hugo-coder.netlify.app/posts/html-and-css-only-tabs/). :)

What do you think?

**Comment by LordMathis** [comment]
Hi @jens1o sounds like a good idea. I'm open to PR. Otherwise I will get to it in a few weeks.

**Comment by LordMathis** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Visibility of tags/taxonomies inside single.html](https://trello.com/c/RSqUK0S1/35-visibility-of-tags-taxonomies-inside-singlehtml)

**Comment by jens1o** [comment]
Thank you very much! :)
