### ISSUE TITLE
Page content oveflowing when on mobile

### ISSUE THREAD

**Issue by kcindric** [LordMathis/hugo-theme-nightfall#21]
Hi! Really like the simplicity and coolness of your theme! I have an issue though, when viewing my posts on mobile the page content is overflowing as shown here:
<img width="399" alt="image" src="https://github.com/LordMathis/hugo-theme-nightfall/assets/44549361/b136da6e-8c97-4f9b-bd6f-5451c06ad1f1">

Is this expected behavior? I tried removing any images I have on a page and just using vanilla markdown but I face the same issue.

Here's a direct link to my webpage, with only one post for now, where you can see that problem happening:
https://www.kcindric.me/posts/psql-full-text-search/

**Comment by LordMathis** [comment]
Thanks for reporting the issue. The problem is with `margin 0 auto` in content class. It needs to be converted to flexbox to keep the content centered. I will take a look at it next week.
