### ISSUE TITLE
live demo

### ISSUE THREAD

**Issue by sunuazizrahayu** [LordMathis/hugo-theme-nightfall#35]
please add live demo of this theme

**Comment by LordMathis** [comment]
While this might be a good idea it is a very low priority for me. The theme is quite simple, what you see on screenshots is pretty much what you get. I don't think live demo would provide that much added value. You can test the theme using the data from the exampleSite folder.

**Comment by sunuazizrahayu** [comment]
when i browse to find a theme, i prefer to check an online demo. so i got an UX of theme without install it on my current system.

you might add github-action to generate static files and deploy with your current repo public url -> [https://lordmathis.github.io/hugo-theme-nightfall/](https://lordmathis.github.io/hugo-theme-nightfall/)
