### ISSUE TITLE
target="_blank" in social links on homepage

### ISSUE THREAD

**Issue by pthoelken** [LordMathis/hugo-theme-nightfall#37]
Is there a way to configure it like the code markdown below? 

```
[[params.social]]
key = 0
name = "github"
url = "https://github.com/gohugoio"
icon = "fa-brands fa-github"
newtabopen = true
```

So that means, that the visitor opens the link in a new tab instead of leaving the my homepage.

**Comment by LordMathis** [comment]
No it's not currently possible but it can be easily implemented. It could work similarly to how rel = "me" works currently. I'll welcome a PR, otherwise I will look at it over the weekend

**Comment by pthoelken** [comment]
I've already patch this. I'll do a MR today.
