### ISSUE TITLE
Error to get sass

### ISSUE THREAD

**Issue by renanbastos93** [LordMathis/hugo-theme-nightfall#39]
`hugo --theme github.com/LordMathis/hugo-theme-nightfall`

ERROR TOCSS-DART: failed to transform "/sass/main.scss" (text/x-scss). You need dart-sass-embedded in your system $PATH.: this feature is not available in your current Hugo version, see https://goo.gl/YMrWcn for more information

**Comment by LordMathis** [comment]
The instructions how to use the theme including the dart-sass requirement and a link dart-sass install guide are in the theme's README

**Comment by renanbastos93** [comment]
Thanks!
