### ISSUE TITLE
Footer for copyleft licenses

### ISSUE THREAD

**Issue by Harshil-Jani** [LordMathis/hugo-theme-nightfall#6]
### Feature Request
We have used hugo with nightfall theme and there was an issue which we had with the footer since it has a copyright but the project uses copyleft license. So, Currently we have forked the repo and used it as per use case. But we think it would be nice if in the `config.toml` we have an option like `footerText : "Something here"`. 

Refer https://github.com/rust-bitcoin/www.rust-bitcoin.org/issues/1

**Comment by LordMathis** [comment]
You can now specify custom html in footer with `footerHtml` option in `[[params]]`

**Comment by Harshil-Jani** [comment]
Thanks for doing this.

**Comment by tcharding** [comment]
Wow, so quick - thanks a bunhc @LordMathis
