### ISSUE TITLE
How to make an about page without published date/reading time info

### ISSUE THREAD

**Issue by mutageneral** [LordMathis/hugo-theme-nightfall#8]
I'm trying to make an about page just like you: https://namesny.com/about/

But when I did `hugo new about.md`, it gives me the published date and reading time like if it was an article. How do I change this?

**Comment by LordMathis** [comment]
My website was generated using an earlier version of the theme which didn't have the metadata section yet. At the moment it is not possible to disable the metadata on page by page basis but there should be.

I think there should be something in front matter like `showMetadata` and if set to false it would not render the published date and other metadata.

I will look at it over the weekend, or you can submit a PR

**Comment by mutageneral** [comment]
This is my first time using Hugo, so I'm still really bad, so I don't think I can fix this yet as I'm still trying to figure out everything. But thank you a lot for the theme and looking into it.
